image: gradle:alpine

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    gradle --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

pages:
  stage: build
  script:
  - sudo nohup java -jar /home/gitlab-runnerbuild/build/libs/*.jar &
  artifacts:
    paths:
      - build/libs/*.jar
  only:
  - master

deploy:
  stage: build
  script:
    - sudo nohup java -jar /home/gitlab-runnerbuild/build/libs/*.jar &

after_script:
  - echo "Feito"