image: docker
services:
  - docker:dind

stages:
  - build
  - package_master
  - package_dev
  - deploy_master
  - deploy_dev

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  image: gradle:5.0-jdk8-alpine
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

package_master:
  stage: package_master
  script:
    - docker build -t registry.gitlab.com/cristiano.gregio/antenas-integracao-master .
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
    - docker push registry.gitlab.com/cristiano.gregio/antenas-integracao-master
  only:
    - master
  except:
    - dev

package_dev:
  stage: package_dev
  script:
    - docker build -t registry.gitlab.com/cristiano.gregio/antenas-integracao-master .
    - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
    - docker push registry.gitlab.com/cristiano.gregio/antenas-integracao-master
  only:
    - dev
  except:
    - master

deploy_master:
  stage: deploy_master
  script:
    - apk upgrade && apk update
    - apk add openssh-client
    - apk add sshpass
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER docker pull registry.gitlab.com/cristiano.gregio/antenas-integracao-master
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER "docker container stop master && docker container rm master || true"
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER docker run --name master -p 8081:8081 -d registry.gitlab.com/cristiano.gregio/antenas-integracao-master
  environment:
    name: prod
    url: http://localhost:8081
  only:
    - master
  except:
    - dev

deploy_dev:
  stage: deploy_dev
  script:
    - apk upgrade && apk update
    - apk add openssh-client
    - apk add sshpass
    - echo $SERVER_PASSWORD
    - echo $SERVER_USER
    - echo $SERVER
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER docker pull registry.gitlab.com/cristiano.gregio/antenas-integracao-master:dev
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER "docker container stop dev && docker container rm dev || true"
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER docker run --name dev -p 8082:8082 -d registry.gitlab.com/cristiano.gregio/antenas-integracao-dev
  environment:
    name: dev
    url: http://localhost:8082
  only:
    - dev
  except:
    - master